version: "3.8"
services:

  kong-db-postgres:
    image: postgres:13
    container_name: kong-db-postgres
    shm_size: 128mb
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - kong-db-postgres-volume:/var/lib/postgresql/data
    ports:
      - 15432:5432
    networks:
      - kong-net
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "kong",
          "-U",
          "kong"
        ]
      timeout: 45s
      interval: 10s
      retries: 10

  kong-db-pgadmin:
    image: "dpage/pgadmin4:8.4"
    container_name: kong-db-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kong@kong.com
      PGADMIN_DEFAULT_PASSWORD: kong
    ports:
      - 8080:80
    depends_on:
      - kong-db-postgres
    volumes:
      - kong-db-pgadmin-volume:/var/lib/pgadmin
    networks:
      - kong-net

  kong-migrations:
    image: kong/kong-gateway:3.6.1.1
    container_name: kong-migrations
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db-postgres
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kong
    networks:
      - kong-net
    depends_on:
      - kong-db-postgres

  kong-gateway:
    image: kong/kong-gateway:3.6.1.1
    container_name: kong-gateway
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db-postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    networks:
      - kong-net
    depends_on:
      - kong-migrations



volumes:
  kong-db-postgres-volume:
    external: true
  kong-db-pgadmin-volume:
    external: true

networks:
  kong-net:
    external: true
