version: "3.8"
services:

  kong-db-postgres:
    image: postgres:13
    container_name: kong-db-postgres
    shm_size: 128mb
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - kong-db-postgres-volume:/var/lib/postgresql/data
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "kong", "-U", "admin"]
      timeout: 45s
      interval: 10s
      retries: 10

  kong-gateway:
    image: kong/kong-gateway:3.6.1.1
    container_name: kong-gateway
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db-postgres
      - KONG_PG_USER=admin
      - KONG_PG_PASSWORD=admin
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    networks:
      - kong-net
    depends_on:
      - kong-db-postgres

  keycloak-db-postgres:
    image: postgres:13
    container_name: keycloak-db-postgres
    shm_size: 128mb
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/db/keycloak:/var/lib/postgresql/data
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "admin"]
      timeout: 45s
      interval: 10s
      retries: 10

  keycloak:
    image: bitnami/keycloak:23.0.7
    container_name: keycloak
    ports:
      - '8081:8080'
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KEYCLOAK_DATABASE_HOST: keycloak-db-postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: admin
      KEYCLOAK_DATABASE_PASSWORD: admin
    networks:
      - kong-net
    depends_on:
      - keycloak-db-postgres


  pgadmin:
    image: "dpage/pgadmin4:8.4"
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8082:80
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    networks:
      - kong-net

volumes:
  kong-db-postgres-volume:
    external: true
  pgadmin-volume:
    external: true

networks:
  kong-net:
    external: true
