version: '3.8'

services:
  backend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    container_name: backend
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - kong-net

networks:
  kong-net:
    external: true
