export const devopsData = [
    { id: 1, tema: "Introdução ao DevOps e Práticas de Desenvolvimento Colaborativo" },
    { id: 2, tema: "Contêineres: Conceitos Fundamentais e Uso do Docker" },
    { id: 3, tema: "Gerenciamento de Contêineres com Podman" },
    { id: 4, tema: "Orquestração de Contêineres com Kubernetes" },
    { id: 5, tema: "Monitoramento de Infraestrutura com Grafana" },
    { id: 6, tema: "Coleta e Visualização de Métricas com Prometheus" },
    { id: 7, tema: "Testes de Email com MailHog em Ambientes de Desenvolvimento" },
    { id: 8, tema: "Processamento de Eventos com Apache Kafka" },
    { id: 9, tema: "Sistema de Mensagens com RabbitMQ" },
    { id: 10, tema: "Padrões e Arquiteturas de Microserviços" },
    { id: 11, tema: "Controle de Versão e Colaboração com Git" },
    { id: 12, tema: "Centralização de Logs com Graylog" },
    { id: 13, tema: "Armazenamento em Cache com Redis" },
    { id: 14, tema: "Autenticação e Autorização com Keycloak" },
    { id: 15, tema: "Integração de Diretórios com LDAP" },
    { id: 16, tema: "Configuração de Servidor de Email (SMTP)" },
    { id: 17, tema: "Busca e Análise de Dados com Elasticsearch" },
    { id: 18, tema: "Gerenciamento de Alertas com Alert Manager" },
    { id: 19, tema: "Monitoramento de Aplicações Spring Boot com Spring Boot Admin" },
    { id: 20, tema: "Padrões de Arquitetura de Software: Arquitetura Hexagonal" },
    { id: 21, tema: "Melhores Práticas de Caching em Aplicações Web" },
    { id: 22, tema: "Autenticação e Autorização com OAuth2" },
    { id: 23, tema: "Gerenciamento de Logs em Aplicações Distribuídas" },
    { id: 24, tema: "Visualização e Monitoramento de Dados com RedisInsight" },
    { id: 25, tema: "Implantação Automatizada de Aplicações com Ansible" },
    { id: 26, tema: "Configuração de Ambientes com Vagrant" },
    { id: 27, tema: "Gestão de Configuração com Puppet" },
    { id: 28, tema: "Provisionamento de Infraestrutura com Terraform" },
    { id: 29, tema: "Monitoramento de Logs com ELK Stack (Elasticsearch, Logstash, Kibana)" },
    { id: 30, tema: "Implantação de Aplicações com Helm Charts" },
    { id: 31, tema: "Automação de Testes com Selenium e Docker" },
    { id: 32, tema: "Segurança de Contêineres e Imagens com Docker Bench Security" },
    { id: 33, tema: "Implantação de Aplicações Java em Containers" },
    { id: 34, tema: "Implantação de Aplicações .NET em Containers" },
    { id: 35, tema: "Implantação de Aplicações Python em Containers" },
    { id: 36, tema: "Escalabilidade e Balanceamento de Carga com Kubernetes" },
    { id: 37, tema: "Autenticação de Aplicações com OAuth2 e Keycloak" },
    { id: 38, tema: "Configuração de Ambientes de Desenvolvimento com Docker Compose" },
    { id: 39, tema: "Gerenciamento de Dados com Docker Volumes e Bind Mounts" },
    { id: 40, tema: "Desenvolvimento e Implantação de Aplicações Node.js em Containers" },
    { id: 41, tema: "Implantação de Aplicações Ruby on Rails em Containers" },
    { id: 42, tema: "Integração Contínua e Entrega Contínua (CI/CD) com Jenkins e Docker" },
    { id: 43, tema: "Desenvolvimento de Aplicações Baseadas em Eventos com Kafka e Docker" },
    { id: 44, tema: "Implantação de Sistemas Distribuídos com Docker Swarm" },
    { id: 45, tema: "Gerenciamento de Configuração de Infraestrutura com Ansible e Docker" },
    { id: 46, tema: "Implantação de Aplicações PHP em Containers" },
    { id: 47, tema: "Monitoramento de Aplicações .NET Core com Prometheus e Grafana" },
    { id: 48, tema: "Monitoramento de Aplicações Java com Micrometer e Prometheus" },
    { id: 49, tema: "Monitoramento de Aplicações Python com Prometheus e Grafana" },
    { id: 50, tema: "Monitoramento de Aplicações Node.js com Prometheus e Grafana" },
    { id: 51, tema: "Integração de Métricas de Aplicações com Prometheus Pushgateway" },
    { id: 52, tema: "Implantação de Aplicações Go em Containers" },
    { id: 53, tema: "Implantação de Aplicações Swift em Containers" },
    { id: 54, tema: "Implantação de Aplicações Kotlin em Containers" },
    { id: 55, tema: "Implantação de Aplicações Rust em Containers" },
    { id: 56, tema: "Implantação de Aplicações Scala em Containers" },
    { id: 57, tema: "Implantação de Aplicações Clojure em Containers" },
    { id: 58, tema: "Implantação de Aplicações Elixir em Containers" },
    { id: 59, tema: "Implantação de Aplicações Erlang em Containers" },
    { id: 60, tema: "Implantação de Aplicações Haskell em Containers" },
    { id: 61, tema: "Implantação de Aplicações Lua em Containers" },
    { id: 62, tema: "Implantação de Aplicações Perl em Containers" },
    { id: 63, tema: "Implantação de Aplicações Tcl em Containers" },
    { id: 64, tema: "Implantação de Aplicações R em Containers" },
    { id: 65, tema: "Implantação de Aplicações Julia em Containers" },
    { id: 66, tema: "Implantação de Aplicações Dart em Containers" },
    { id: 67, tema: "Implantação de Aplicações Objective-C em Containers" },
    { id: 68, tema: "Implantação de Aplicações Groovy em Containers" },
    { id: 69, tema: "Implantação de Aplicações Lua em Containers" },
    { id: 70, tema: "Implantação de Aplicações PHP em Containers" },
    { id: 71, tema: "Implantação de Aplicações Ruby em Containers" },
    { id: 72, tema: "Implantação de Aplicações Swift em Containers" },
    { id: 73, tema: "Implantação de Aplicações Kotlin em Containers" },
    { id: 74, tema: "Implantação de Aplicações Rust em Containers" },
    { id: 75, tema: "Implantação de Aplicações Scala em Containers" },
    { id: 76, tema: "Implantação de Aplicações Clojure em Containers" },
    { id: 77, tema: "Implantação de Aplicações Elixir em Containers" },
    { id: 78, tema: "Implantação de Aplicações Erlang em Containers" },
    { id: 79, tema: "Implantação de Aplicações Haskell em Containers" },
    { id: 80, tema: "Implantação de Aplicações Lua em Containers" },
    { id: 81, tema: "Implantação de Aplicações Perl em Containers" },
    { id: 82, tema: "Implantação de Aplicações Tcl em Containers" },
    { id: 83, tema: "Implantação de Aplicações R em Containers" },
    { id: 84, tema: "Implantação de Aplicações Julia em Containers" },
    { id: 85, tema: "Implantação de Aplicações Dart em Containers" },
    { id: 86, tema: "Implantação de Aplicações Objective-C em Containers" },
    { id: 87, tema: "Implantação de Aplicações Groovy em Containers" },
    { id: 88, tema: "Implantação de Aplicações Lua em Containers" },
    { id: 89, tema: "Implantação de Aplicações PHP em Containers" },
    { id: 90, tema: "Implantação de Aplicações Ruby em Containers" },
    { id: 91, tema: "Implantação de Aplicações Swift em Containers" },
    { id: 92, tema: "Implantação de Aplicações Kotlin em Containers" },
    { id: 93, tema: "Implantação de Aplicações Rust em Containers" },
    { id: 94, tema: "Implantação de Aplicações Scala em Containers" },
    { id: 95, tema: "Implantação de Aplicações Clojure em Containers" },
    { id: 96, tema: "Implantação de Aplicações Elixir em Containers" },
    { id: 97, tema: "Implantação de Aplicações Erlang em Containers" },
    { id: 98, tema: "Implantação de Aplicações Haskell em Containers" },
    { id: 99, tema: "Implantação de Aplicações Lua em Containers" },
    { id: 100, tema: "Implantação de Aplicações Perl em Containers" }
];
