export const iaData = [
    { id: 1, tema: "Introdução à Inteligência Artificial" },
    { id: 2, tema: "Neurônios Artificiais e Redes Neurais Simples" },
    { id: 3, tema: "Backpropagation e Treinamento de Redes Neurais" },
    { id: 4, tema: "Deep Learning e Redes Neurais Profundas" },
    { id: 5, tema: "Visão Computacional e Reconhecimento de Imagem" },
    { id: 6, tema: "Processamento de Linguagem Natural (NLP)" },
    { id: 7, tema: "Geração de Texto com Modelos de Linguagem" },
    { id: 8, tema: "Speech-to-Text e Reconhecimento de Fala" },
    { id: 9, tema: "Reconhecimento de Voz e Comandos de Voz" },
    { id: 10, tema: "IA Generativa e Redes Generativas Adversariais (GANs)" },
    { id: 11, tema: "Aprendizado por Reforço (Reinforcement Learning)" },
    { id: 12, tema: "OpenAI's Language Models (LLMs)" },
    { id: 13, tema: "Aplicações de IA em Ciência de Dados e Análise Preditiva" },
    { id: 14, tema: "Robótica e Inteligência Artificial" },
    { id: 15, tema: "IA na Indústria: Otimização de Processos e Produção" },
    { id: 16, tema: "Agentes Inteligentes e Sistemas Multiagente" },
    { id: 17, tema: "Ética e Responsabilidade na Inteligência Artificial" },
    { id: 18, tema: "Interpretabilidade e Explicabilidade em Modelos de IA" },
    { id: 19, tema: "Redes Neurais Convolucionais (CNNs)" },
    { id: 20, tema: "Redes Neurais Recorrentes (RNNs) e LSTMs" },
    { id: 21, tema: "Autoencoders e Representação de Dados" },
    { id: 22, tema: "Transfer Learning e Fine-Tuning em Modelos de IA" },
    { id: 23, tema: "Detecção de Anomalias e Segurança em IA" },
    { id: 24, tema: "IA em Finanças: Previsão de Mercados e Riscos" },
    { id: 25, tema: "IA em Jogos: Estratégia e Aprendizado de Máquina" },
    { id: 26, tema: "IA na Educação: Personalização e Aprendizado Adaptativo" },
    { id: 27, tema: "IA em Energia: Otimização de Redes e Sistemas" },
    { id: 28, tema: "IA em Transportes: Veículos Autônomos e Logística" },
    { id: 29, tema: "IA na Agricultura: Monitoramento e Agricultura de Precisão" },
    { id: 30, tema: "IA em Serviços: Chatbots e Atendimento ao Cliente" },
    { id: 31, tema: "IA em Música: Composição e Análise Musical" },
    { id: 32, tema: "IA em Arte: Criação e Geração de Arte Digital" },
    { id: 33, tema: "IA em Esportes: Análise de Desempenho e Estratégia" },
    { id: 34, tema: "IA em Saúde Mental: Diagnóstico e Acompanhamento" },
    { id: 35, tema: "IA em Bioinformática: Genômica e Análise de Sequências" },
    { id: 36, tema: "IA em Seguros: Previsão de Riscos e Fraud" },
    { id: 37, tema: "IA em Recursos Humanos: Recrutamento e Seleção" },
    { id: 38, tema: "IA em Varejo: Personalização e Recomendação de Produtos" },
    { id: 39, tema: "IA em Realidade Aumentada e Virtual" },
    { id: 40, tema: "IA em Cidades Inteligentes: Gestão Urbana e Sustentabilidade" },
    { id: 41, tema: "IA em Astronomia: Análise de Dados e Descoberta de Exoplanetas" },
    { id: 42, tema: "IA em Ciência dos Materiais: Descoberta e Desenvolvimento" },
    { id: 43, tema: "IA em Logística: Roteirização e Otimização de Transporte" },
    { id: 44, tema: "IA em Turismo: Recomendação e Personalização de Viagens" },
    { id: 45, tema: "IA em Governo: Eficiência e Transparência" },
    { id: 46, tema: "IA em Filmes e Entretenimento: Análise de Audiência e Roteiros" },
    { id: 47, tema: "IA em Vídeo Games: Inteligência Artificial em NPCs" },
    { id: 48, tema: "IA em Energias Renováveis: Otimização e Previsão" },
    { id: 49, tema: "IA em Linguística Computacional e Processamento de Linguagem Natural" },
    { id: 50, tema: "IA em Psicologia: Modelagem e Diagnóstico" },
    { id: 51, tema: "IA em Neurociência: Modelagem de Redes Neurais Biológicas" },
    { id: 52, tema: "IA em Logística Reversa e Sustentabilidade" },
    { id: 53, tema: "IA em Medicina: Diagnóstico e Tratamento Assistido" },
    { id: 54, tema: "IA em Design: Geração Automática e Otimização" },
    { id: 55, tema: "IA em Engenharia: Otimização de Processos e Projetos" },
    { id: 56, tema: "IA em Química: Descoberta de Moléculas e Reações" },
    { id: 57, tema: "IA em Geologia: Análise de Dados Geoespaciais" },
    { id: 58, tema: "IA em Ensino: Tutoriais e Personalização de Aprendizado" },
    { id: 59, tema: "IA em Tecnologia Assistiva: Acessibilidade e Inclusão" },
    { id: 60, tema: "IA em Recursos Naturais: Monitoramento e Conservação" },
    { id: 61, tema: "IA em Arte Generativa e Criação Colaborativa" },
    { id: 62, tema: "IA em Biologia Computacional: Modelagem de Sistemas Biológicos" },
    { id: 63, tema: "IA em História: Análise de Dados e Reconstrução de Eventos" },
    { id: 64, tema: "IA em Publicidade: Segmentação e Personalização de Anúncios" },
    { id: 65, tema: "IA em Nanotecnologia: Design e Simulação de Nanoestruturas" },
    { id: 66, tema: "IA em Gestão de Riscos: Previsão e Mitigação" },
    { id: 67, tema: "IA em Psiquiatria: Diagnóstico e Aconselhamento" },
    { id: 68, tema: "IA em Engenharia Civil: Otimização de Estruturas e Projetos" },
    { id: 69, tema: "IA em Marketing: Análise de Mercado e Comportamento do Consumidor" },
    { id: 70, tema: "IA em Farmacologia: Descoberta de Fármacos e Toxicidade" },
    { id: 71, tema: "IA em Meteorologia: Previsão do Tempo e Clima" },
    { id: 72, tema: "IA em Espionagem e Segurança Nacional" },
    { id: 73, tema: "IA em Criminologia: Análise de Perfil e Prevenção" },
    { id: 74, tema: "IA em Filantropia: Otimização de Doações e Impacto Social" },
    { id: 75, tema: "IA em Energia Nuclear: Segurança e Gestão de Rejeitos" },
    { id: 76, tema: "IA em Religião: Análise de Textos Sagrados e Crenças" },
    { id: 77, tema: "IA em FinTech: Inovação e Disrupção Financeira" },
    { id: 78, tema: "IA em Zoologia: Monitoramento e Conservação de Espécies" },
    { id: 79, tema: "IA em Arqueologia: Análise de Dados e Reconstrução de Civilizações" },
    { id: 80, tema: "IA em Direito: Análise Jurídica e Previsão de Decisões" },
    { id: 81, tema: "IA em Transporte Público: Otimização e Planejamento de Rotas" },
    { id: 82, tema: "IA em Biometria: Reconhecimento Facial e Biométrico" },
    { id: 83, tema: "IA em Educação Financeira: Análise e Orientação" },
    { id: 84, tema: "IA em Mídia: Recomendação de Conteúdo e Personalização" },
    { id: 85, tema: "IA em Voz sobre IP (VoIP): Análise e Melhorias" },
    { id: 86, tema: "IA em Previsão de Desastres Naturais: Monitoramento e Alertas" },
    { id: 87, tema: "IA em Arquitetura: Otimização e Design Sustentável" },
    { id: 88, tema: "IA em Desenvolvimento Sustentável: Otimização de Recursos e Projetos" },
    { id: 89, tema: "IA em Saúde Pública: Análise Epidemiológica e Prevenção" },
    { id: 90, tema: "IA em Moda: Análise de Tendências e Personalização de Estilo" },
    { id: 91, tema: "IA em Telecomunicações: Otimização de Redes e Serviços" },
    { id: 92, tema: "IA em Neurotecnologia: Interfaces Cérebro-Computador" },
    { id: 93, tema: "IA em Biologia Marinha: Monitoramento e Conservação" },
    { id: 94, tema: "IA em Música Eletrônica: Composição e Mixagem Automatizadas" },
    { id: 95, tema: "IA em Escrita Criativa: Geração e Análise de Textos" },
    { id: 96, tema: "IA em Educação Ambiental: Sensibilização e Engajamento" },
    { id: 97, tema: "IA em Biblioteconomia: Organização e Recuperação de Informação" },
    { id: 98, tema: "IA em Astrobiologia: Busca por Vida Extraterrestre e Ambientes Habitáveis" },
    { id: 99, tema: "IA em Consultoria: Análise de Dados e Recomendações Estratégicas" },
    { id: 100, tema: "IA na Saúde: Diagnóstico Médico Assistido por IA" }
];
